-- MySQL Script generated by MySQL Workbench
-- Thu Aug 22 17:17:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `Nombre` VARCHAR(16) NOT NULL,
  `Apellido` VARCHAR(20) NOT NULL,
  `ID_Usuario` INT(6) NOT NULL,
  `Telefono` INT(10) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Contraseña` VARCHAR(16) NOT NULL,
  `CP` INT(5) NOT NULL,
  `Edad` INT(2) NOT NULL,
  `Direccion` VARCHAR(120) NOT NULL,
  `Correo` VARCHAR(20) NOT NULL,
  `Foto` BLOB(1) NOT NULL,
  `Calificacion` INT(1) NOT NULL,
  PRIMARY KEY (`ID_Usuario`),
  UNIQUE INDEX `correo_UNIQUE` (`Correo` ASC) VISIBLE,
  UNIQUE INDEX `ID_usuario_UNIQUE` (`ID_Usuario` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`publicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`publicaciones` (
  `ID_Publicacion` INT(12) NOT NULL,
  `Proveedor/Cliente` TINYINT NULL DEFAULT 1,
  `Fecha_Hora` DATETIME NOT NULL,
  `Nombre` VARCHAR(16) NOT NULL,
  `Apellidos` VARCHAR(20) NOT NULL,
  `Descripcion` TINYTEXT NOT NULL,
  `Adjunto` BLOB(1) NULL DEFAULT NULL,
  `Ubicacion` VARCHAR(120) NOT NULL,
  `Tipo_Servicio` VARCHAR(45) NOT NULL,
  `Foto_Usuario` BLOB(1) NOT NULL,
  `ID_Usuario` INT(6) NOT NULL,
  PRIMARY KEY (`ID_Publicacion`),
  UNIQUE INDEX `ID_publicacion_UNIQUE` (`ID_Publicacion` ASC) VISIBLE,
  INDEX `fk_publicaciones_usuario_idx` (`ID_Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_publicaciones_usuario`
    FOREIGN KEY (`ID_Usuario`)
    REFERENCES `mydb`.`usuario` (`ID_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chats` (
  `ID_Chat` INT(10) NOT NULL AUTO_INCREMENT,
  `ID_Usuario` INT(6) NOT NULL,
  PRIMARY KEY (`ID_Chat`),
  INDEX `fk_chats_usuario1_idx` (`ID_Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_chats_usuario1`
    FOREIGN KEY (`ID_Usuario`)
    REFERENCES `mydb`.`usuario` (`ID_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mensajes` (
  `ID_Mensaje` INT(10) NOT NULL AUTO_INCREMENT,
  `Nombre_Destinatario` VARCHAR(16) NOT NULL,
  `Nombre_Remitente` VARCHAR(16) NOT NULL,
  `ID_Destinatario` INT(6) NOT NULL,
  `ID_Remitente` INT(6) NOT NULL,
  `Foto_Destinatario` BLOB NOT NULL,
  `Foto_Remitente` BLOB NOT NULL,
  `Descripcion` TINYTEXT NOT NULL,
  `Fecha_Hora` DATETIME NOT NULL,
  `chats_ID_Chat` INT(10) NOT NULL,
  PRIMARY KEY (`ID_Mensaje`, `chats_ID_Chat`),
  UNIQUE INDEX `id_chat_UNIQUE` (`ID_Mensaje` ASC) VISIBLE,
  INDEX `fk_mensajes_chats1_idx` (`chats_ID_Chat` ASC) VISIBLE,
  CONSTRAINT `fk_mensajes_chats1`
    FOREIGN KEY (`chats_ID_Chat`)
    REFERENCES `mydb`.`chats` (`ID_Chat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comentarios` (
  `ID_Comentario` INT NOT NULL AUTO_INCREMENT,
  `Comentario` VARCHAR(255) NULL,
  `ID_Publicacion` INT(12) NOT NULL,
  `ID_Usuario` INT(6) NOT NULL,
  PRIMARY KEY (`ID_Comentario`),
  UNIQUE INDEX `Id_interaccion_UNIQUE` (`ID_Comentario` ASC) VISIBLE,
  INDEX `fk_reacciones_publicaciones1_idx` (`ID_Publicacion` ASC) VISIBLE,
  INDEX `fk_reacciones_usuario1_idx` (`ID_Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_reacciones_publicaciones1`
    FOREIGN KEY (`ID_Publicacion`)
    REFERENCES `mydb`.`publicaciones` (`ID_Publicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reacciones_usuario1`
    FOREIGN KEY (`ID_Usuario`)
    REFERENCES `mydb`.`usuario` (`ID_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Reaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reaccion` (
  `ID_Ikonic` INT NOT NULL,
  `ID_Publicacion` INT(12) NOT NULL,
  `ID_Usuario` INT(6) NOT NULL,
  PRIMARY KEY (`ID_Ikonic`),
  UNIQUE INDEX `ID_Ikonic_UNIQUE` (`ID_Ikonic` ASC) VISIBLE,
  INDEX `fk_Reaccion_publicaciones1_idx` (`ID_Publicacion` ASC) VISIBLE,
  INDEX `fk_Reaccion_usuario1_idx` (`ID_Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Reaccion_publicaciones1`
    FOREIGN KEY (`ID_Publicacion`)
    REFERENCES `mydb`.`publicaciones` (`ID_Publicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reaccion_usuario1`
    FOREIGN KEY (`ID_Usuario`)
    REFERENCES `mydb`.`usuario` (`ID_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
